### ISSUE TITLE
Lost field focus

### ISSUE THREAD

**Issue by zxcvbn2949** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#15]
Context menu(right click on field) stops working with this addon for Fast Word Query [https://ankiweb.net/shared/info/1807206748](url) or editor: paste raw unfiltered full html [https://ankiweb.net/shared/info/1765712663](url). It lost field focus.

**Comment by zxcvbn2949** [comment]
Context menu - Cut not working too.

**Comment by ijgnd** [comment]
thanks for this report.

I tried my add-on with "Fast Word Query" and got an error message that originates from "Fast Word Query". Fast word query has some internal config about each field of a note type and somehow didn't include my manually added source_field which I have at the end of my note type so that it has the highest field index. When you right click a field fast word query seems to compare the current field index with this internal config. Since fast word quers's internal config wasn't updated a bug occured. I doubt that there's anything that I can do about it.

The problem disappeared after I opened and did some random modifications I don't remember and closed the config of the Fast Word query.

If you have a traceback that lists my add-on in the error message please post it so that I now where to look.

I'm closing this for the moment but reopen it if you have more.

**Comment by zxcvbn2949** [comment]
But what about these1Editor - Context menu - paste raw unfiltered full html https://ankiweb.net/shared/info/1765712663 lost field focus.2 Editor - Context menu - Cut not working.15.01.2021, 02:40, "ijgnd" <notifications@github.com>:
thanks for this report.
I tried my add-on with "Fast Word Query" and got an error message that originates from "Fast Word Query". Fast word query has some internal config about each field of a note type and somehow didn't include my manually added source_field which I have at the end of my note type so that it has the highest field index. When you right click a field fast word query seems to compare the current field index with this internal config. Since fast word quers's internal config wasn't updated a bug occured. I doubt that there's anything that I can do about it.
The problem disappeared after I opened and did some random modifications I don't remember and closed the config of the Fast Word query.
If you have a traceback that lists my add-on in the error message please post it so that I now where to look.
I'm closing this for the moment but reopen it if you have more.

**Comment by ijgnd** [comment]
I just retried and now see what you mean. It happens with the pdf add-on alone. I'll upload a fix later today or tomorrow.

Thanks for replying again.

**Comment by zxcvbn2949** [comment]
Ok, thank you.18.01.2021, 13:15, "ijgnd" <notifications@github.com>:
I just retried and now see what you mean. It happens with the pdf add-on alone. I'll upload a fix later today or tomorrow.
Thanks for replying again.

**Comment by ijgnd** [comment]
It took a bit longer but I finally uploaded the new version. If it still doesn't work please let me know.

**Comment by zxcvbn2949** [comment]
Thanks now it works fine.23.01.2021, 18:43, "ijgnd" <notifications@github.com>:
It took a bit longer but I finally uploaded the new version. If it still doesn't work please let me know.
