### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by iterating** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#3]
Debug info:
Anki 2.1.15 (442df9d6) Python 3.8.4 Qt 5.14.2 PyQt 5.15.0
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons possibly involved: Open linked pdf docx epub audiovideo etc in external Program
Caught exception:
```
  File "/usr/share/anki/aqt/webview.py", line 27, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/share/anki/aqt/webview.py", line 87, in _onCmd
    return self._onBridgeCmd(str)
  File "/usr/share/anki/aqt/webview.py", line 386, in _onBridgeCmd
    return self.onBridgeCmd(cmd)
  File "<decorator-gen-60>", line 2, in _linkHandler
  File "/usr/share/anki/anki/hooks.py", line 74, in decorator_wrapper
    return repl(*args, **kwargs)
  File "/usr/share/anki/anki/hooks.py", line 71, in repl
    return new(_old=old, *args, **kwargs)
  File "/home/iterating/.local/share/Anki2/addons21/879473266/open_in_external.py", line 82, in myLinkHandler
    open_external(file, page)
  File "/home/iterating/.local/share/Anki2/addons21/879473266/open_in_external.py", line 75, in open_external
    subprocess.Popen(args)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
<class 'PermissionError'>: [Errno 13] Permission denied: 
```
>I'm on Anki 2.1.16 on Debian.

**Comment by ijgnd** [comment]
I don't use debian testing so I have no idea.

I tested with debian stable and Anki from its repo. The add-on works for me even with this old anki version. I know that I set the minimal required version to 2.1.15 on ankiweb but apparently it still works in 2.1.8 from the stable repo if you manage to install the anki addon.

On debian stable the binary from apps.ankiweb.net for 2.1.15 (and later) works for me - at least if you install the latest update that I upload after you created this issue. I don't believe that it helps in your case since the anki from the repo should use the appropriate paths but maybe it does? 

Apart from this: I have no idea what config you use. https://tracker.debian.org/pkg/anki has a big warning on top  "Marked for autoremoval on 31 July". So I'm not really motivated to investigate about this version.

If Anki is still in the bullseye repo once it becomes stable I'll try again.

**Comment by ijgnd** [comment]
what command have you set in your config? does it have the appropriate permissions?


my add-on just runs the command "subprocess.Popen" from the python standard library, see [here](https://github.com/ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program/blob/33440d05ed129a7d55a1ccf2bc3e0b4243f7f868/src/open_in_external.py#L81). To get the parameters you could just add `print(args)` in front of it and then run anki from the cli and then 

a) check what happens if you subprocess.Popen from outside of Anki with the parameters printed
b) run subprocess.Popen from the anki debug console, https://docs.ankiweb.net/#/misc?id=debug-console

if a) does not work it's not a problem with Anki. if it works it's a problem with my anki or my add-on. If b) does not work it's not a problem with only my add-on.

you could post the results.

&nbsp;

The Anki main page also has this, https://apps.ankiweb.net/ :

> Some Linux distributions include Anki in their repositories. We've seen many users experience problems with these distributed versions, due to them being out of date or missing appropriate libraries. For this reason, the compiled package above is recommended over using the version of Anki bundled with your Linux distribution. 

Indeed the most recent Anki 2.1.28 has many improvements over 2.1.15.

**Comment by iterating** [comment]
Thanks for your prompt reply. On your suggestion I installed the latest
Anki (2.1.28) and your add-on is working perfectly.

Can you share a little about how you personally use Anki as a "frontend" to
your personal knowledge database? My general process so far is
outlining/mindmapping to study, Anki cards for facts, and links to the
mindmap and PDF on the cards to provide context. Seeing your Anki
developments, I thought you might be walking a similar path. I'd love to
hear some of your experiences and refinements in your own digital
organization and Anki learning process!

-John

**Comment by ijgnd** [comment]
I think I have a pretty regular workflow which is similar to yours..

I try to include a source in my notes so that later when I'm in doubt about the fact or I have forgotten the context I can look it up. For regular study I usually don't look at the pdf files unless it's a special case like a huge table, schematic, image, etc. that would look bad in my small Anki window. When I'm dealing with digital sources I can automate opening it on the right page ...  Sometimes I skip parts of a book or article and have a note/card that I have rescheduled far into the future with a comment like "you skipped the info box (top paragraphs)". Then later I can quickly do this missing stuff.
